contracts/Liquidator.sol, contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol, contracts/interfaces/ILiquidator.sol, contracts/test/Liquidator.t.sol
=> feat: Add destination to liquidator, make tests run faster (SC-3984)

contracts/interfaces/Interfaces.sol, contracts/test/Liquidator.t.sol, contracts/test/mocks/Mocks.sol
=> chore: Move rebalancer 

README.md
=> feat: Add README

contracts/Liquidator.sol
And prevent re-entrancy in `liquidatePortion`.
=> chore: CEI (event emissions before interactions, where possible) (SC-4151)

contracts/Liquidator.sol, contracts/test/Liquidator.t.sol
Addresses ToB issue [#12](https://github.com/maple-labs/trail-of-bits-audit/issues/12).
=> feat: Add require on transfer and EOA OTC liquidation test (SC-4180)

contracts/Liquidator.sol, contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol, contracts/interfaces/ILiquidator.sol, contracts/interfaces/IUniswapV2StyleStrategy.sol, contracts/interfaces/Interfaces.sol, contracts/test/Liquidator.t.sol
=> feat: Add max return amount

contracts/Liquidator.sol
=> chore: ToB audit branch

contracts/Liquidator.sol
=> feat: ToB audit branch

contracts/Liquidator.sol, contracts/test/Liquidator.t.sol
=> fix: Add input validation to constructor (SC-4265)

contracts/Liquidator.sol, contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol, contracts/interfaces/ILiquidator.sol, contracts/interfaces/IUniswapV2StyleStrategy.sol, contracts/interfaces/Interfaces.sol, contracts/test/Liquidator.t.sol, contracts/test/mocks/Mocks.sol
=> feat: Pause functionality + reentrancy modifier (SC-4270)

contracts/test/Liquidator.t.sol, contracts/test/accounts/Owner.sol, contracts/test/mocks/Mocks.sol
Addresses https://github.com/code-423n4/2021-12-maple-findings/issues/23
=> fix: Strict 0.8.7 (C4 #23)

contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol
Addressse https://github.com/code-423n4/2021-12-maple-findings/issues/3
=> fix: Shorten require messages (C4 #3)

contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol
Addresses https://github.com/code-423n4/2021-12-maple-findings/issues/55
=> fix: Use constant instead of block.timestamp (C4 #55)

contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol
Addresses https://github.com/code-423n4/2021-12-maple-findings/issues/52
=> fix: Unchecked approve (C4 #52)

contracts/Liquidator.sol
Easier to just have the PoolDelegate pull funds via the DebtLocker in an emergency, and liquidate elsewhere, than to allow changes to the liquidator after deploy
Addresses: https://github.com/code-423n4/2021-12-maple-findings/issues/7
=> fix: Use immutables (C4 #7)

.gitmodules, contracts/interfaces/ILiquidator.sol, contracts/interfaces/IUniswapV2StyleStrategy.sol, contracts/interfaces/Interfaces.sol, contracts/test/Liquidator.t.sol, contracts/test/mocks/Mocks.sol
- typos
- spacing
- return variable names
- alignment
- git module relic
=> chore: cleanup

contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol, contracts/test/Liquidator.t.sol
=> fix: Balance check in swap function can cause DoS (c4 #35)

contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol, contracts/interfaces/IUniswapV2StyleStrategy.sol, contracts/interfaces/Interfaces.sol, contracts/test/Liquidator.t.sol, contracts/test/mocks/Mocks.sol
=> feat: Improve strategy and cleanup

.circleci/config.yml, .gitignore, contracts/Liquidator.sol, contracts/SushiswapStrategy.sol, contracts/UniswapV2Strategy.sol, contracts/interfaces/ILiquidator.sol, contracts/interfaces/IUniswapV2StyleStrategy.sol, contracts/test/mocks/Mocks.sol, package.yaml
=> chore: natspec, whitespace, checksums, cleanup [Wait for deps]

README.md
=> feat:  README update (SC-4527)
